// AUTO-GENERATED by gen_tb.py -- array-level power-activity testbench for the
// synthesized AMXFP4_SystolicArray netlist. Every primary-input bus gets fresh uniform-random
// bits each cycle (high-activity, uncorrelated data); a backward-SAIF is dumped
// over a steady-state window for SAIF-annotated power. Functional correctness is
// irrelevant -- only representative switching activity.
`timescale 1ns/10ps

module tb;
    localparam int WARMUP  = 64;
    localparam int CAPTURE = 4000;
    localparam int SHIFT_PERIOD = 32;

    logic clk = 1'b0;
    logic rst_n;
    logic acc_shift;

    logic [27:0] amxfp4_a_scale_pos_in;
    logic [27:0] amxfp4_a_scale_pos_out;
    logic [27:0] amxfp4_a_scale_neg_in;
    logic [27:0] amxfp4_a_scale_neg_out;
    logic [511:0] amxfp4_a_elem_in;
    logic [511:0] amxfp4_a_elem_out;
    logic [27:0] amxfp4_b_scale_pos_in;
    logic [27:0] amxfp4_b_scale_pos_out;
    logic [27:0] amxfp4_b_scale_neg_in;
    logic [27:0] amxfp4_b_scale_neg_out;
    logic [511:0] amxfp4_b_elem_in;
    logic [511:0] amxfp4_b_elem_out;
    logic [3:0] acc_sign_in;
    logic [3:0] acc_sign_out;
    logic [31:0] acc_exp_in;
    logic [31:0] acc_exp_out;
    logic [91:0] acc_mant_in;
    logic [91:0] acc_mant_out;

    AMXFP4_SystolicArray dut (
        .clk(clk), .rst_n(rst_n), .acc_shift(acc_shift),
        .amxfp4_a_scale_pos_in(amxfp4_a_scale_pos_in), .amxfp4_a_scale_pos_out(amxfp4_a_scale_pos_out),
        .amxfp4_a_scale_neg_in(amxfp4_a_scale_neg_in), .amxfp4_a_scale_neg_out(amxfp4_a_scale_neg_out),
        .amxfp4_a_elem_in(amxfp4_a_elem_in), .amxfp4_a_elem_out(amxfp4_a_elem_out),
        .amxfp4_b_scale_pos_in(amxfp4_b_scale_pos_in), .amxfp4_b_scale_pos_out(amxfp4_b_scale_pos_out),
        .amxfp4_b_scale_neg_in(amxfp4_b_scale_neg_in), .amxfp4_b_scale_neg_out(amxfp4_b_scale_neg_out),
        .amxfp4_b_elem_in(amxfp4_b_elem_in), .amxfp4_b_elem_out(amxfp4_b_elem_out),
        .acc_sign_in(acc_sign_in), .acc_sign_out(acc_sign_out),
        .acc_exp_in(acc_exp_in), .acc_exp_out(acc_exp_out),
        .acc_mant_in(acc_mant_in), .acc_mant_out(acc_mant_out)
    );

    // 2 ns clock (matches 500 MHz synthesis target)
    always #1 clk = ~clk;

    task automatic drive_random;
        amxfp4_a_scale_pos_in[0 +: 28] = $random;
        amxfp4_a_scale_neg_in[0 +: 28] = $random;
        for (int k = 0; k < 16; k++) amxfp4_a_elem_in[k*32 +: 32] = $random;
        amxfp4_b_scale_pos_in[0 +: 28] = $random;
        amxfp4_b_scale_neg_in[0 +: 28] = $random;
        for (int k = 0; k < 16; k++) amxfp4_b_elem_in[k*32 +: 32] = $random;
        acc_sign_in[0 +: 4] = $random;
        for (int k = 0; k < 1; k++) acc_exp_in[k*32 +: 32] = $random;
        for (int k = 0; k < 2; k++) acc_mant_in[k*32 +: 32] = $random;
        acc_mant_in[64 +: 28] = $random;
    endtask

    initial begin
        rst_n = 1'b0; acc_shift = 1'b0;
        repeat (4) @(posedge clk);
        rst_n = 1'b1;

        for (int c = 0; c < WARMUP; c++) begin
            @(negedge clk);
            drive_random();
            acc_shift = (c % SHIFT_PERIOD == SHIFT_PERIOD-1);
        end

        $set_toggle_region(tb.dut);
        $toggle_start;
        for (int c = 0; c < CAPTURE; c++) begin
            @(negedge clk);
            drive_random();
            acc_shift = (c % SHIFT_PERIOD == SHIFT_PERIOD-1);
        end
        $toggle_stop;
        $toggle_report("AMXFP4_SystolicArray.saif", 1.0e-9, "tb.dut");

        $display("[tb] AMXFP4 SAIF capture complete: %0d cycles", CAPTURE);
        $finish;
    end
endmodule
