seed: 5000

model:
  model_type: "Qwen/Qwen2.5-14B"

dataset:
  name: "wikitext"
  path: "wikitext-2-raw-v1"
  split: "test"

save:
  run_dir: "save/llm/qwen2.5-14b-fp16-wikitext/"
  logger: "inference.log"

eval:
  seq_len: 2048
  stride: 2036

quantization:
  wbit: 16
  abit: 16
  wqtype: identity
  xqtype: identity
  num_samples: 2048
  rescale_out: False

train:
  batch_size: 2048

smooth:
  alpha: 0.85
  flag: False

t2c:
  swl: 32
  sfl: 26
  save_model: False
  save_tensors: False

export:
  export_samples: 0
