// AUTO-GENERATED by gen_tb.py -- array-level power-activity testbench for the
// synthesized INT8_SystolicArray netlist. Every primary-input bus gets fresh uniform-random
// bits each cycle (high-activity, uncorrelated data); a backward-SAIF is dumped
// over a steady-state window for SAIF-annotated power. Functional correctness is
// irrelevant -- only representative switching activity.
`timescale 1ns/10ps

module tb;
    localparam int WARMUP  = 64;
    localparam int CAPTURE = 4000;
    localparam int SHIFT_PERIOD = 32;

    logic clk = 1'b0;
    logic rst_n;
    logic acc_shift;

    logic [1023:0] a_in;
    logic [1023:0] a_out;
    logic [1023:0] b_in;
    logic [1023:0] b_out;
    logic [127:0] acc_in;
    logic [127:0] acc_out;

    INT8_SystolicArray dut (
        .clk(clk), .rst_n(rst_n), .acc_shift(acc_shift),
        .a_in(a_in), .a_out(a_out),
        .b_in(b_in), .b_out(b_out),
        .acc_in(acc_in), .acc_out(acc_out)
    );

    // 2 ns clock (matches 500 MHz synthesis target)
    always #1 clk = ~clk;

    task automatic drive_random;
        for (int k = 0; k < 32; k++) a_in[k*32 +: 32] = $random;
        for (int k = 0; k < 32; k++) b_in[k*32 +: 32] = $random;
        for (int k = 0; k < 4; k++) acc_in[k*32 +: 32] = $random;
    endtask

    initial begin
        rst_n = 1'b0; acc_shift = 1'b0;
        repeat (4) @(posedge clk);
        rst_n = 1'b1;

        for (int c = 0; c < WARMUP; c++) begin
            @(negedge clk);
            drive_random();
            acc_shift = (c % SHIFT_PERIOD == SHIFT_PERIOD-1);
        end

        $set_toggle_region(tb.dut);
        $toggle_start;
        for (int c = 0; c < CAPTURE; c++) begin
            @(negedge clk);
            drive_random();
            acc_shift = (c % SHIFT_PERIOD == SHIFT_PERIOD-1);
        end
        $toggle_stop;
        $toggle_report("INT8_SystolicArray.saif", 1.0e-9, "tb.dut");

        $display("[tb] INT8 SAIF capture complete: %0d cycles", CAPTURE);
        $finish;
    end
endmodule
