seed: 5000
model:
  model_type: llava-hf/llava-onevision-qwen2-7b-ov-hf
save:
  run_dir: save/llava-onevision-7b-nvfp4-seedbench2plus/
  logger: inference.log
eval:
  benchmarks:
  - seedbench2plus
quantization:
  vision:
    wbit: 4
    abit: 4
    wqtype: nvfp4_quant
    xqtype: nvfp4_quant
    w_block_size: 16
    a_block_size: 16
    quantize_bmm_input: true
    bmm_qtype: nvfp4
    bmm_block_size: 16
  projector:
    wbit: 4
    abit: 4
    wqtype: nvfp4_quant
    xqtype: nvfp4_quant
    w_block_size: 16
    a_block_size: 16
  llm:
    wbit: 4
    abit: 4
    wqtype: nvfp4_quant
    xqtype: nvfp4_quant
    w_block_size: 16
    a_block_size: 16
    quantize_bmm_input: true
    bmm_qtype: nvfp4
    bmm_block_size: 16
    num_samples: 128
    rescale_out: false
smooth:
  alpha: 0.85
  flag: false
