#!/usr/bin/env python3
"""Generate per-design array-level power testbenches + DC power tcl for the
SAIF-annotated power flow. Every primary-input bus is driven with fresh
uniform-random bits each cycle (high-activity, uncorrelated-data operating
point), acc_shift pulses every 32 cycles to exercise the shift-out mux, and a
backward-SAIF is dumped over a steady-state window. Each input port X_in has a
matching output port X_out of equal width (systolic pass-through + accumulator),
so outputs are derived by name."""
import os

WARMUP, CAPTURE, SHIFT_PERIOD = 64, 4000, 32

# design -> (top_module, syn_subdir, [(input_port, width), ...])
# widths: ROWS=COLS=4 (group=32) unless noted; FP16 is 32x32.
ACC4 = [("acc_sign_in", 4), ("acc_exp_in", 32), ("acc_mant_in", 92)]
DESIGNS = {
 "INT4": ("INT4_SystolicArray", "INT4",
    [("a_in",512),("b_in",512),("acc_in",128)]),
 "INT8": ("INT8_SystolicArray", "INT8",
    [("a_in",1024),("b_in",1024),("acc_in",128)]),
 "MXINT4": ("MXINT4_SystolicArray", "MXINT4",
    [("mxint_a_exp_in",32),("mxint_a_mant_in",512),("mxint_b_exp_in",32),("mxint_b_mant_in",512)]+ACC4),
 "MXINT4_g16": ("MXINT4_g16_SystolicArray", "MXINT4_g16",
    [("mxint_a_exp_in",64),("mxint_a_mant_in",512),("mxint_b_exp_in",64),("mxint_b_mant_in",512)]+ACC4),
 "MXFP4": ("MXFP4_SystolicArray", "MXFP4",
    [("mxfp4_a_exp_in",32),("mxfp4_a_elem_in",512),("mxfp4_b_exp_in",32),("mxfp4_b_elem_in",512)]+ACC4),
 "MXFP4_g16": ("MXFP4_g16_SystolicArray", "MXFP4_g16",
    [("mxfp4_a_exp_in",64),("mxfp4_a_elem_in",512),("mxfp4_b_exp_in",64),("mxfp4_b_elem_in",512)]+ACC4),
 "NVFP4": ("NVFP4_SystolicArray", "NVFP4",
    [("nvfp4_a_scale_in",64),("nvfp4_a_elem_in",512),("nvfp4_b_scale_in",64),("nvfp4_b_elem_in",512)]+ACC4),
 "AMXFP4": ("AMXFP4_SystolicArray", "AMXFP4",
    [("amxfp4_a_scale_pos_in",28),("amxfp4_a_scale_neg_in",28),("amxfp4_a_elem_in",512),
     ("amxfp4_b_scale_pos_in",28),("amxfp4_b_scale_neg_in",28),("amxfp4_b_elem_in",512)]+ACC4),
 "MXFP4_PLUS": ("MXFP4_PLUS_SystolicArray", "MXFP4_PLUS",
    [("a_exp_in",32),("a_elem_in",512),("a_bm_idx_in",20),
     ("b_exp_in",32),("b_elem_in",512),("b_bm_idx_in",20)]+ACC4),
 "MiX425b_MXINT4": ("MiX425b_MXINT4_SystolicArray", "MiX425b_MXINT4",
    [("mxint_exp_in",32),("mxint_mant_in",512),("invmx_max_base_exp_in",20),
     ("invmx_sign_in",128),("invmx_exp_in",384),("invmx_mant_in",12)]+ACC4),
 "MiX425b_MXFP4": ("MiX425b_MXFP4_SystolicArray", "MiX425b_MXFP4",
    [("mxfp4_exp_in",32),("mxfp4_elem_in",512),("invmx_max_base_exp_in",20),
     ("invmx_sign_in",128),("invmx_exp_in",384),("invmx_mant_in",12)]+ACC4),
 "MiX45b_MXINT4": ("MiX45b_MXINT4_SystolicArray", "MiX45b_MXINT4",
    [("mxint_exp_in",64),("mxint_mant_in",512),("invmx_max_base_exp_in",20),
     ("invmx_sign_in",128),("invmx_exp_in",384),("invmx_mant_in",48)]+ACC4),
 "MiX45b_MXFP4": ("MiX45b_MXFP4_SystolicArray", "MiX45b_MXFP4",
    [("mxfp4_exp_in",64),("mxfp4_elem_in",512),("invmx_max_base_exp_in",20),
     ("invmx_sign_in",128),("invmx_exp_in",384),("invmx_mant_in",48)]+ACC4),
 "MiX45b_MXINT5": ("MiX45b_MXINT5_SystolicArray", "MiX45b_MXINT5",
    [("mxint_exp_in",64),("mxint_mant_in",640),("invmx_max_base_exp_in",20),
     ("invmx_sign_in",128),("invmx_exp_in",384),("invmx_mant_in",48)]+ACC4),
 "FP16": ("FP16_SystolicArray", "FP16",
    [("fp16_a_in",512),("fp16_b_in",512),("acc_sign_in",32),("acc_exp_in",256),("acc_mant_in",736)]),
}

# SITE CONFIGURATION: directory holding the .db timing library, and the .db file
# name -- the same two values you set in syn/<Design>/syn.tcl.
# Paper used TSMC 28nm tcbn28hpcplusbwp30p140ssg0p81v125c.db.
LIB = "<PATH-TO-DIRECTORY-CONTAINING-THE-.db-TIMING-LIBRARY>"
TARGET_DB = "<STANDARD-CELL-TIMING-LIBRARY>.db"
OPCOND = "<OPERATING-CONDITION-NAME>"

def fill_lines(port, w, indent="        "):
    """Emit SV lines to slam random bits onto a port of width w."""
    out = []
    nch = w // 32
    rem = w % 32
    if nch > 0:
        out.append(f"{indent}for (int k = 0; k < {nch}; k++) {port}[k*32 +: 32] = $random;")
    if rem > 0:
        out.append(f"{indent}{port}[{nch*32} +: {rem}] = $random;")
    return out

def gen_tb(design, top, ports):
    sigs, conns, drive = [], ["        .clk(clk), .rst_n(rst_n), .acc_shift(acc_shift)"], []
    for name, w in ports:
        oname = name[:-3] + "_out"
        sigs.append(f"    logic [{w-1}:0] {name};")
        sigs.append(f"    logic [{w-1}:0] {oname};")
        conns.append(f"        .{name}({name}), .{oname}({oname})")
        drive += fill_lines(name, w)
    sig_blk = "\n".join(sigs)
    conn_blk = ",\n".join(conns)
    drive_blk = "\n".join(drive)
    return f"""// AUTO-GENERATED by gen_tb.py -- array-level power-activity testbench for the
// synthesized {top} netlist. Every primary-input bus gets fresh uniform-random
// bits each cycle (high-activity, uncorrelated data); a backward-SAIF is dumped
// over a steady-state window for SAIF-annotated power. Functional correctness is
// irrelevant -- only representative switching activity.
`timescale 1ns/10ps

module tb;
    localparam int WARMUP  = {WARMUP};
    localparam int CAPTURE = {CAPTURE};
    localparam int SHIFT_PERIOD = {SHIFT_PERIOD};

    logic clk = 1'b0;
    logic rst_n;
    logic acc_shift;

{sig_blk}

    {top} dut (
{conn_blk}
    );

    // 2 ns clock (matches 500 MHz synthesis target)
    always #1 clk = ~clk;

    task automatic drive_random;
{drive_blk}
    endtask

    initial begin
        rst_n = 1'b0; acc_shift = 1'b0;
        repeat (4) @(posedge clk);
        rst_n = 1'b1;

        for (int c = 0; c < WARMUP; c++) begin
            @(negedge clk);
            drive_random();
            acc_shift = (c % SHIFT_PERIOD == SHIFT_PERIOD-1);
        end

        $set_toggle_region(tb.dut);
        $toggle_start;
        for (int c = 0; c < CAPTURE; c++) begin
            @(negedge clk);
            drive_random();
            acc_shift = (c % SHIFT_PERIOD == SHIFT_PERIOD-1);
        end
        $toggle_stop;
        $toggle_report("{top}.saif", 1.0e-9, "tb.dut");

        $display("[tb] {design} SAIF capture complete: %0d cycles", CAPTURE);
        $finish;
    end
endmodule
"""

def gen_tcl(design, top, syn):  # noqa
    return f"""# AUTO-GENERATED -- SAIF-annotated power for {design} ({top}).
# Re-powers the already-synthesized .ddc; only switching activity differs.
set top "{top}"
set search_path [list "." "{LIB}"]
set target_library [list "{TARGET_DB}"]
set_app_var target_library [concat $target_library]
set_app_var link_library [concat "*" $target_library]
set LIB_NAME [file rootname "{TARGET_DB}"]

# Requires syn/{syn} to have been run first (it writes the .ddc reused here).
read_file -format ddc "../../syn/{syn}/output/${{top}}.ddc"
current_design $top
link

set_operating_conditions "{OPCOND}" -library $LIB_NAME
create_clock -name clk -period 2 [get_ports clk]

reset_switching_activity
read_saif -input "${{top}}.saif" -instance_name "tb/dut"

report_saif -hier > saif_coverage.rpt
report_power -hier -analysis_effort medium -nosplit > power_saif.rpt
quit
"""

def main():
    base = os.path.dirname(os.path.abspath(__file__))
    for design, (top, syn, ports) in DESIGNS.items():
        d = os.path.join(base, design)
        os.makedirs(d, exist_ok=True)
        with open(os.path.join(d, f"{design.lower()}_power_tb.sv"), "w") as f:
            f.write(gen_tb(design, top, ports))
        with open(os.path.join(d, "power_saif.tcl"), "w") as f:
            f.write(gen_tcl(design, top, syn))
        print(f"{design:18s} top={top:34s} syn=syn/{syn}")

if __name__ == "__main__":
    main()
