seed: 5000
model:
  model_type: openbmb/MiniCPM-V-2_6
save:
  run_dir: save/minicpm-v-mix-4.25b-int4-textvqa/
  logger: inference.log
eval:
  benchmarks:
  - textvqa
quantization:
  vision:
    wbit: 4
    abit: 3
    wqtype: mxint_quant
    xqtype: inverted_mxint_quant
    w_block_size: 32
    a_block_size: 32
    shared_exp_bits: 8
    a_ebit: 3
    mantissa_group_size: 32
    quantize_bmm_input: true
    bmm_qtype: mixed_invmx_mxint
    bmm_bits: 4
    bmm_ebit: 3
    bmm_q_bits: 3
    bmm_q_ebit: 3
    bmm_kv_bits: 4
    bmm_block_size: 32
  projector:
    wbit: 4
    abit: 3
    wqtype: mxint_quant
    xqtype: inverted_mxint_quant
    w_block_size: 32
    a_block_size: 32
    shared_exp_bits: 8
    a_ebit: 3
    mantissa_group_size: 32
  llm:
    wbit: 4
    abit: 3
    wqtype: mxint_quant
    xqtype: inverted_mxint_quant
    w_block_size: 32
    a_block_size: 32
    shared_exp_bits: 8
    mantissa_group_size: 32
    quantize_bmm_input: true
    bmm_qtype: mixed_invmx_mxint
    bmm_bits: 4
    bmm_ebit: 3
    bmm_q_bits: 3
    bmm_kv_bits: 4
    bmm_block_size: 32
    num_samples: 128
    rescale_out: false
    a_ebit: 3
    bmm_q_ebit: 3
smooth:
  alpha: 0.85
  flag: false
